'use strict';
const indexRouter = require('./index');
const usersRouter = require('./api/users');
const filesRouter = require('./api/files');
const passwordsRouter = require('./api/passwords');
const cardsRouter = require('./api/cards');
const messageRouter = require('./api/messages');
const postRouter = require('./api/posts');
const transactionRouter = require('./api/transactions');
const pushRouter = require('./api/pushs');
const bitcoinRouter = require('./api/bitcoins');
const authRouter = require('./api/auth');
const contactRouter = require('./api/contacts');
const utilityRouter = require('./api/utilities');
const affiliateRouter = require('./api/affiliates');
const verificationRouter = require('./api/verifications');
const notificationRouter = require('./api/notifications');
const walletRouter = require('./api/wallet');
const bankAccountRouter = require('./api/bankAccount');
const withdrawalRouter = require('./api/withdrawals');
const apiRouter = require('./api');
module.exports = (app) => {
    //Routes
    app.use('/', indexRouter);
    app.use('/api/v1',apiRouter);
    app.use('/api/v1/users',usersRouter);
    app.use('/api/v1/files',filesRouter);
    app.use('/api/v1/cards',cardsRouter);
    app.use('/api/v1/passwords',passwordsRouter);
    app.use('/api/v1/posts',postRouter);             
    app.use('/api/v1/transactions',transactionRouter);
    app.use('/api/v1/push-tokens',pushRouter);
    app.use('/api/v1/messages',messageRouter);
    app.use('/api/v1/bitcoins',bitcoinRouter);
    app.use('/api/v1/auths',authRouter);
    app.use('/api/v1/contacts',contactRouter);
    app.use('/api/v1/utilities',utilityRouter);
    app.use('/api/v1/affiliates', affiliateRouter);
    app.use('/api/v1/verifications', verificationRouter);
    app.use('/api/v1/notifications', notificationRouter);
    app.use('/api/v1/wallets', walletRouter);
    app.use('/api/v1/bank-accounts', bankAccountRouter);
    app.use('/api/v1/withdrawals', withdrawalRouter);
};
